Application/SampleWebApplication/Controllers/DemosController.cs
using Exam70483Library;
using Exam70483Library.DataAccess;
using Exam70483Library.Managers;
using Exam70483Web.Models.Entity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Globalization;
using System.IO;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Exam70483Web.Controllers
{
    public class DemosController : GenericController
    {
        #region "Campos"
        //
        string connString               = System.Configuration.ConfigurationManager.ConnectionStrings["defaultConnection"].ConnectionString;
        string _documentsLocalDirectory = System.Configuration.ConfigurationManager.AppSettings["DocumentsLocalDirectory"];
        //
        int ARRAY_SIZE = 25;
        #endregion

        #region "Metodos"

        #region "Raiz"
        //
        public ActionResult _DemosIndex(int id = 0)
        {
            //
            try
            {
                //---------------------------------------------------
                // LOG
                //---------------------------------------------------
                LogModel.Log("PAGE_DEMO_INDEX", this.GetIpValue());

            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
            }
            return View();
        }
        //
        #endregion

        #region "PDF DEMO"
        public ActionResult _PDFDemo()
        {
            //
            ViewBag.Message = @"[OBTENER PDF A PARTIR DE HTML Y CSS]";
            //
            try
            {
                //---------------------------------------------------
                // LOG
                //---------------------------------------------------
                LogModel.Log("PAGE_PDF_DEMO", this.GetIpValue());

            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
            }
            return View();
        }
        //
        public string _GetPdf(string subjectName)
        {
            //
            string _extensionDocumento = @"pdf";
            string _directorioDocumento = string.Format("{0}/{1}", _documentsLocalDirectory, _extensionDocumento);
            string status = @"[ok]";

            //
            string fileName = string.Format("{0}{1}.{2}"
             , System.Guid.NewGuid().ToString()
             , DateTime.Now.ToString(Globals.DateFormatShortTimestamp)
             , _extensionDocumento);

            string resultRelativeFilePath = string.Format(@"~/{0}/{1}", _directorioDocumento, fileName);
            //
            string cssPath         = Server.MapPath(@"~/Content/pdf.css");
            string resultFilePath  = Server.MapPath(resultRelativeFilePath);
            string imagePath       = Server.MapPath(@"~/Content/mcsd-cert.jpg");
            string mcsdImagePath   = Server.MapPath(@"~/Content/mcsd.png");
            //
            string constring = System.Configuration.ConfigurationManager.ConnectionStrings["defaultConnection"].ConnectionString;
            //
            try
            {
                //---------------------------------------------------
                // IMAGEN DE ENCABEZADO
                //---------------------------------------------------
                string htmlContent = string.Empty;
                htmlContent += @"<table width=""100%"" cellpadding=""0px"" cellspacing=""0px"" style=""border: solid 0px #000;"">";
                htmlContent += string.Format(@"<tr><td align=""center"" style=""width:100%;border:0px;""><img src=""{0}""></img></td></tr>", imagePath);
                htmlContent += @"</table>";
                // NO ES POSIBLE CARGAR LA IMAGEN DESDE CSS
                //htmlContent      += string.Format(@"<div style=""background-image: url(""{0}""); background-repeat: no-repeat; height: 250px;"">&nbsp;</div>",mcsdImagePath);   
                //
                //---------------------------------------------------
                // AÑADIR FORMATO EXTERNO
                //---------------------------------------------------
                string wrapperhtml = string.Empty;
                using (var streamReader = new System.IO.StreamReader(Server.MapPath(@"~/Content/Resultados.html"), System.Text.Encoding.UTF8))
                {
                    wrapperhtml = streamReader.ReadToEnd();
                    streamReader.Close();
                }
                //
                string currentDate = DateTime.Now.ToString("dddd, dd MMMM yyyy", new CultureInfo("es-CO"));
                //
                wrapperhtml = wrapperhtml.Replace("[CONTENT]", subjectName);
                wrapperhtml = wrapperhtml.Replace("[CURRENT_DATE]", currentDate);
                wrapperhtml = wrapperhtml.Replace("[IMAGE]", htmlContent);
                wrapperhtml = wrapperhtml.Replace("[IMAGE_PATH]", mcsdImagePath);
                //    
                status += string.Format("|{0}|{1}|{2}", fileName, resultFilePath, imagePath);
                //
                Exam70483.Libraries.Managers.PDFManager.GetPDFFile(
                        wrapperhtml
                      , cssPath
                      , resultFilePath
                );
            }
            catch (Exception e)
            {
                //
                string errorMsg = string.Format("PDF_ERROR : {0}", e.InnerException.Message + " " + e.StackTrace);
                //
                LogModel.Log(errorMsg, string.Empty, LogModel.LogType.Error);
                //
                status = errorMsg;
            }
            //
            return status;
        }
        #endregion

        #region "CSV ASYNC DEMO"
        //
        public ActionResult _XlsAsyncDemo()
        {
            //
            try
            {
                //---------------------------------------------------
                // LOG
                //---------------------------------------------------
                LogModel.Log("PAGE_CSV_ASYNC_DEMO", this.GetIpValue(), LogModel.LogType.Info);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
            }
            return View();
        }
        //
        public Task<String> SetCSVTaskAsync()
        {
            return Task<String>.Factory.StartNew(() =>
            {
                //
                string status = "ok";
                //
                try
                {
                    //------------------------------------------------------------------------------------------------------
                    // OBTENER DATOS
                    //------------------------------------------------------------------------------------------------------
                    DataTable maestroListado = PersonasModel.ListadoPersonasDataTable();

                    //------------------------------------------------------------------------------------------------------
                    // DECLARACION DE VARIABLES
                    //------------------------------------------------------------------------------------------------------
                    Exam70483Library.Globals.AsyncTaskType asyncType = Exam70483Library.Globals.AsyncTaskType.CSVExnacato;
                    string rootPath = Server.MapPath("~/");
                    //------------------------------------------------------------------------------------------------------
                    // INSTANCIACION DE CLASE 
                    //------------------------------------------------------------------------------------------------------
                    //
                    CSVManager csvManager = new CSVManager
                        (
                              asyncType
                            , maestroListado
                            , rootPath
                        );
                    status = csvManager.GetCSV();

                    //------------------------------------------------------------------------------------------------------
                    // LOG
                    //------------------------------------------------------------------------------------------------------
#if DEBUG
                    LogModel.Log("CSV_ASYNC");

                    LogModel.Log(string.Format("ROOT_PATH : {0}", rootPath));

                    LogModel.Log(string.Format("ROOT_FILE : {0}", status));

                    LogModel.Log(string.Format("RECORD_AMT : {0}", maestroListado.Rows.Count));
#endif

                }
                catch (Exception e)
                {
                    //
                    string errorMsg = string.Format("CSV_ERROR : {0}", e.InnerException.Message + " " + e.StackTrace);
                    //
                    LogModel.Log(errorMsg, string.Empty, LogModel.LogType.Error);
                    //
                    status = errorMsg;
                }

                return status;

            });
        }
        #endregion

        #region "ZIP ASYNC DEMO"
        //
        public ActionResult _ZipDemo()
        {
            //
            try
            {
                //---------------------------------------------------
                // LOG
                //---------------------------------------------------
                LogModel.Log("PAGE_ZIP_DEMO", this.GetIpValue(), LogModel.LogType.Info);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
            }
            return View();

        }
        //
        [HttpPost]
        public ActionResult _ZipDemo(HttpPostedFileBase UploadFileCtrl)
        {
            //
            if (UploadFileCtrl != null && UploadFileCtrl.ContentLength > 0)
                //
                try
                {
                    //
                    string path = Path.Combine(Server.MapPath("~/Output/UploadedFiles"),

Application/SampleWebApplication/Views/Demos/_DemosIndex.cshtml
@{
    ViewBag.Title = @"[DEMOS - PROGRAMACION]";
}

<style>
    #frameworkDemo {
        font-size: x-small;
    }

    .li_mark a {
        color: #808080;
    }
    .li_submark 
    {
        background-color: orangered;
        font-size       : xx-small;
    }
    .li_submark a 
    {
        color: #0000ff;
    }
</style>
<div class="main-container">
    <div class="content">
        <div class="content-body">
            <p>@ViewBag.Title</p>
        </div>
    </div>
    <hr />
    <div>
        <P>
            <select id="frameworkDemo">
                <option selected="selected" value="0">SELECCIONE LENGUAJES</option>
                <option selected="selected" value="1">[C#/MVC][JQUERY][CSS][XHTML]</option>
                <option selected="selected" value="2">[C#/MVC][JQUERY][CSS][XHTML][TYPESCRIPT]</option>
            </select>
            NOTACION:<mark class="li_submark" style="padding-left:10px">&nbsp;</mark> = "EN CONSTRUCCION"
        </P>
    </div>
    <div style="padding-left:20px;font-size:xx-small;">
        <ol id="frameworkDemo_1" style="display:none;">
            <li>@Html.ActionLink("[DISTANCIA MAS CORTA]"         , "_DijkstraDemo"               , "Demos")</li>
            <li>@Html.ActionLink("[ALGORITMOS DE ORDENAMIENTO]"  , "_SortBenchMarkDemo"          , "Demos")</li>
            <li>@Html.ActionLink("[EXPRESIONES REGULARES]"       , "_RegExDemo"                  , "Demos")</li>
            <li>@Html.ActionLink("[GENERAR ARCHIVO ZIP]"         , "_ZipDemo"                    , "Demos")</li>
            <li>@Html.ActionLink("[GENERAR ARCHIVO PDF]"         , "_PdfDemo"                    , "Demos")</li>
            <li>@Html.ActionLink("[GENERAR ARCHIVO CSV]"         , "_XlsAsyncDemo"               , "Demos")</li>
            <li>@Html.ActionLink("[LOG DE VISITAS]"              , "_LogDemo"                    , "Demos")</li>
            <!--<li><a href="javascript:void window.open('https://procesos.ramajudicial.gov.co/procesoscs/')">[BUSQUEDA DE PROCESOS JUDICIALES]</a></li>-->
        </ol>
        <ol id="frameworkDemo_2" style="display:none;">
            <li class="li_submark">
                @Html.ActionLink("[RED NEURONAL]"                , "_NeuralNetworkDemo"          , "Demos")
            </li>
        </ol>
    </div>
    <hr />
    <a>@Html.ActionLink("[HOME]", "Index", "Home")</a>
</div>

<script>
    //
    $(document).ready(function () {
        //
        console.log("LOADING PAGE DEMOS");
        //
        _EvalUrl();
    })
    //
    $("#frameworkDemo").change(function () {
        //
        var selectedValue = $("#frameworkDemo").val();
        //
        console.log("Selected Value " + selectedValue);
        //
        _SelectItem(selectedValue);
    });
    //
    function _EvalUrl() {
        //
        var queries       = {};
        var selectedValue = 0;
        //
        $.each(document.location.search.substr(1).split('&'), function (c, q) {
            //
            var i = q.split('=');
            //
            if (i.length > 1)
            {
                //
                queries[i[0].toString()] = i[1].toString();
                //
                console.log('ITERATION : ' + '[' + c + ']=' + q);
                //
                console.log('URL : ' + '[' + i[1].toString() + ']=' + queries[i[0].toString()]);
            }
        });
        //
        if (queries["lang"] != null) {
            //
            selectedValue = queries["lang"];
            //
            console.log('Selected Item : ' + selectedValue);
        }
        //
        $("#frameworkDemo").val(selectedValue);
        //
        _SelectItem(selectedValue);
    }
    //
    function _SelectItem(selectedValue)
    {
        switch (selectedValue) {
            //
            case "0":
                //
                $("#frameworkDemo_1").attr("style", "display:none;");
                $("#frameworkDemo_2").attr("style", "display:none;");
                //
                console.log($("#frameworkDemo_1").attr("style"));
                //
                break;
            case "1":
                //
                $("#frameworkDemo_1").attr("style", "display:inline;");
                $("#frameworkDemo_2").attr("style", "display:none;");
                //
                console.log($("#frameworkDemo_1").attr("style"));
                //
                break;
            case "2":
                //
                $("#frameworkDemo_1").attr("style", "display:none;");
                $("#frameworkDemo_2").attr("style", "display:inline;");
                //
                console.log($("#frameworkDemo_2").attr("style"));
                //
                break;
        }

    }

</script>

Application/SampleWebApplication/Views/Demos/_LogDemo.cshtml
@model IEnumerable<Exam70483Web.Models.Entity.AccessLogEntity>
@{
    ViewBag.Title = @"[LOG DEMO]";
}

<style>
    /*------------------------------------------------*/
    /* ESTILOS STATUS DE OPERACION                    */
    /*------------------------------------------------*/
    .modalStatus {
        display: none; /* Hidden by default */
        position: fixed; /* Stay in place */
        z-index: 99; /* Sit on top */
        left: 0;
        top: 0;
        width: 100%; /* Full width */
        height: 100%; /* Full height */
        overflow: auto; /* Enable scroll if needed */
        background-color: rgb(0,0,0); /* Fallback color */
        background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    }

    .modalStatus-content {
        text-align: center;
        background-color: #fefefe;
        margin: 15% auto; /* 15% from the top and centered */
        padding: 1em;
        border: 1px solid #888;
        width: 100%; /* Could be more or less, depending on screen size */
        color: black;
    }
</style>

<div class="main-container">
    <div class="content">
        <div class="content-body">
            <p>@ViewBag.Title</p>
        </div>
        <hr />
        <div id="gridContainer" style="font-size:xx-small;">
            <!-- INICIO LISTADO -->
            @{
                WebGrid gridInputOutput = new WebGrid
                (
                  Model
                , canPage: true
                , rowsPerPage: 10
                , canSort: false
                );
            }

            @gridInputOutput.GetHtml(

                mode: WebGridPagerModes.All,

                firstText: "Primero",
                previousText: "Anterior",
                nextText: "Siguiente",
                lastText: "Ultimo",

                tableStyle: "grid-view",
                headerStyle: "grid-view-header",
                rowStyle: "grid-view-tr-normal",
                alternatingRowStyle: "grid-view-tr-alternate",
                footerStyle: "grid-view-pgr",

                columns: gridInputOutput.Columns
                (
                    // 1) ID_COLUMN
                    // gridInputOutput.Column("Id_Column", "ID_COLUMN"),
                    // 0) PAGE_NAME
                    gridInputOutput.Column("PageName", "PAGE NAME"),
                    // 2) ACCESS_DATE
                    gridInputOutput.Column("AccessDate", "ACCESS DATE"),
                    // 3) IP_VALUE
                    gridInputOutput.Column("IpValue", "IP ORIGEN")
                )
             )
            <!-- FIN LISTADO    -->
        </div>
        <hr />
        <div>
            <input type="button" id="btnGenerarInforme" value="[Generar Informe XLS]"/>
        </div>
        <hr />
        <div>
            <a href="#" id="DownloadFile">[Descargar Informe XLS]</a>
        </div>
        <hr />
        <a href="../Demos/_DemosIndex?lang=1">Volver al Menú</a>
        <!-- INICIO VENTANA MODAL TRANSCURSO OPERACION -->
        <div id="statusWindow" class="modalStatus" style="display:none">
            <div class="modalStatus-content">
                ... Procesando ...
            </div>
        </div>
        <!-- FIN VENTANA MODAL TRANSCURSO DE OPERACION -->
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        try
        {
            //
            console.log("ENTRANDO A PAGINA LOG DEMO");
        }
        catch (error) {
            //
            console.error(error);
            //
            alert('error cargando pagina');
        }
    });
    //
    $("#btnGenerarInforme").click(function () {
        //
        _ShowProgressBar();
        //
        console.log("GENERANDO INFORME XLS");
        //
        var p_url = "GenerarInformeXLS";
        //
        $.ajax({
            url: p_url
        })
        .done(function (data) {
            //
            console.log("RESULTADO FUNCION : " + data);
            //
            if (data === "[ERROR]") 
            {
                //
                alert("ERROR EN FUNCION");
            }
            else
            {
                //
                var urlFile      = '../Output/xlsx/' + data;
                var downloadLink = DebugHostingContent("javascript:void window.open('" + urlFile + "');");
                //
                 $("#DownloadFile").attr("href", downloadLink );
                //
                alert("SE GENERO CORRECTAMENTE EL ARCHIVO");
            }
            //
            _HideProgressBar();
            //
            return true;
        })
        .fail(function (jqXHR, textStatus, errorThrown) {
            //
            _HideProgressBar();
            //
            console.log('ERROR EN FUNCION : ' + textStatus);
            //
            console.log('ERROR EN FUNCION : ' + errorThrown);
            //
            alert("ERROR EN FUNCION");
            //
            return false;
        });
    });
    //
    //
    function DebugHostingContent(msg) {
        //
        console.log("cadena a evaular : " + msg);

        //
        let regEx = /(.*)(<!--SCRIPT GENERATED BY SERVER! PLEASE REMOVE-->)(.*\w+.*)(<!--SCRIPT GENERATED BY SERVER! PLEASE REMOVE-->)(.*)/;
        //
        var strMsg = msg.replace(/(\r\n|\n|\r)/gm, "");
        //
        var matches = strMsg.match(regEx);

        if (matches != null) {
            //
            for (var index = 1; index < matches.length; index++) {
                //
                var matchValue = matches[index];
                //        
                console.log("coincidencia : " + matchValue);

                //
                if ((matchValue.indexOf("<!--SCRIPT GENERATED BY SERVER! PLEASE REMOVE-->") != -1) && (matchValue.trim() != "")) {
                    //
                    strMsg = strMsg.replace(matchValue, "");
                    //
                    console.log("REEMPLAZANDO. NUEVA CADENA : " + strMsg);
                }

                //
                if ((matchValue.indexOf("<center>") != -1) && (matchValue.trim() != "")) {
                    //
                    strMsg = strMsg.replace(matchValue, "");
                    //
                    console.log("REEMPLAZANDO. NUEVA CADENA : " + strMsg);
                }
            }
        }
        else
            console.log("NO_HAY_COINCIDENCIAS");

        //
        console.log("CADENA DEPURADA : " + strMsg);

        //
        return strMsg;
    }
    //
    function _ShowProgressBar() {
        //
        var modal = document.getElementById("statusWindow");
        modal.style.display = "block";
        //
        console.log('status window show');
        //
    }
    //
    function _HideProgressBar() {
        //
        var modal = document.getElementById("statusWindow");
        modal.style.display = "none";
        modal.style.display = "hidden";
        //
        console.log('status window hide');
        //
    }
</script>

Application/SampleWebApplication/Views/Demos/_NeuralNetworkDemo.cshtml
@{
    ViewBag.Title = @"[NEURAL NETWORK DEMO]";
}

<style>
    /*------------------------------------------------*/
    /* ESTILOS STATUS DE OPERACION                    */
    /*------------------------------------------------*/
    .modalStatus {
        display: none; /* Hidden by default */
        position: fixed; /* Stay in place */
        z-index: 99; /* Sit on top */
        left: 0;
        top: 0;
        width: 100%; /* Full width */
        height: 100%; /* Full height */
        overflow: auto; /* Enable scroll if needed */
        background-color: rgb(0,0,0); /* Fallback color */
        background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    }

    .modalStatus-content {
        text-align: center;
        background-color: #fefefe;
        margin: 15% auto; /* 15% from the top and centered */
        padding: 1em;
        border: 1px solid #888;
        width: 100%; /* Could be more or less, depending on screen size */
        color: black;
    }

</style>

<div class="main-container">
    <div class="content">
        <div class="content-body">
            <p>@ViewBag.Title</p>
            <p>[<a href="javascript: void window.open('#');">(REFERENCIA)</a>]</p>
        </div>
        <hr />
        <div id="signature"></div>
        <hr />
        <div>
            [SOME_FUNCTIONALITY_HERE]
        </div>
        <hr />
        <div>
            <input id="NewData" type="button" title="[REINICIAR]" value="[REINICIAR]" disabled="disabled"></input>
            |
            <input id="SetData" type="button" title="[GENERAR]" value="[GENERAR]"></input>
        </div>
        <hr />
        <a href="../Demos/_DemosIndex?lang=2">Volver al Menú</a>
        <!-- INICIO VENTANA MODAL TRANSCURSO OPERACION -->
        <div id="statusWindow" class="modalStatus" style="display:none">
            <div class="modalStatus-content">
                ... Procesando ...
            </div>
        </div>
        <!-- FIN VENTANA MODAL TRANSCURSO DE OPERACION -->
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        //
        var $sigdiv = $("#signature");

        // inits the jSignature widget.
        $sigdiv.jSignature({
            width: '100%',
            height: '240px'
        });

        // after some doodling...
        $sigdiv.jSignature("reset"); // clears the canvas and rerenders the decor on it.

        // Getting signature as SVG and rendering the SVG within the browser.
        // (!!! inline SVG rendering from IMG element does not work in all browsers !!!)
        // this export plugin returns an array of [mimetype, base64-encoded string of SVG of the signature strokes]
        /*
        var datapair = $sigdiv.jSignature("getData", "svgbase64");
        var i  = new Image();
        i.src  = "data:" + datapair[0] + "," + datapair[1] ;
        $(i).appendTo($("#someelement")); // append the image (SVG) to DOM.

        // Getting signature as "base30" data pair
        // array of [mimetype, string of jSIgnature"s custom Base30-compressed format]
        datapair = $sigdiv.jSignature("getData","base30")
        // reimporting the data into jSignature.
        // import plugins understand data-url-formatted strings like "data:mime;encoding,data"
        $sigdiv.jSignature("setData", "data:" + datapair.join(","))
        */
    });
</script>

Application/SampleWebApplication/Views/Demos/_ZipDemo.cshtml
@{
    ViewBag.Title = @"[COMPRESION        / Zip File        ]";
}

<style>
    /*------------------------------------------------*/
    /* ESTILOS STATUS DE OPERACION                    */
    /*------------------------------------------------*/
    .modalStatus {
        display: none; /* Hidden by default */
        position: fixed; /* Stay in place */
        z-index: 99; /* Sit on top */
        left: 0;
        top: 0;
        width: 100%; /* Full width */
        height: 100%; /* Full height */
        overflow: auto; /* Enable scroll if needed */
        background-color: rgb(0,0,0); /* Fallback color */
        background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    }

    .modalStatus-content {
        text-align:center;
        background-color: #fefefe;
        margin: 15% auto; /* 15% from the top and centered */
        padding: 1em;
        border: 1px solid #888;
        width: 100%; /* Could be more or less, depending on screen size */
        color: black;
    }
</style>

<div class="main-container">
    <div class="content">
        <div class="content-body">
            <p>@ViewBag.Title</p>
            <p>[System.IO.Compression Namespace - <a href="javascript: void window.open('https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.zipfile?view=net-5.0')">"[CLASE "ZipFile"]"</a>]</p>
        </div>
        <hr />
        @using (Html.BeginForm("_ZipDemo",
                        "Demos",
                        FormMethod.Post,
                        new { enctype = "multipart/form-data" }))
        {
            <label for="UploadFileCtrl">Cargar Archivo a Comprimir:</label>
            <input type="file" name="UploadFileCtrl" id="UploadFileCtrl" />
            <br />
            <input type="submit" value="[CARGAR ARCHIVO]" />
            <br />
            <br />
            <span> STATUS : [@ViewBag.Message]</span>
            <br />
        }
        <hr />
        <div>
            <input id="GetZIP" type="button" title="[OBTENER ZIP]" value="[OBTENER ZIP]"></input>
            <hr />
            <a href="#" id="DownloadFile">Descargar ZIP</a>
        </div>
        <hr />
        <a href="../Demos/_DemosIndex?lang=1">Volver al Menú</a>
        <!-- INICIO VENTANA MODAL TRANSCURSO OPERACION -->
        <div id="statusWindow" class="modalStatus" style="display:none">
            <div class="modalStatus-content">
                ... Procesando ...
            </div>
        </div>
        <!-- FIN VENTANA MODAL TRANSCURSO DE OPERACION -->
    </div>
</div>

<script type="text/javascript">
    //
    $(document).ready(function () {
        console.log("LOADING PAGE 7");
    });
    //
    function _ShowProgressBar() {
        //
        var modal = document.getElementById("statusWindow");
        modal.style.display = "block";

        console.log('status window show');
        //
    }
    // 
    function _HideProgressBar() {
        //
        var modal = document.getElementById("statusWindow");
        modal.style.display = "none";
        modal.style.display = "hidden";

        console.log('status window hide');
        //
    }
    //
    function DebugHostingContent(msg) {
        //
        msg = msg.substring(0, 68);
        //
        return msg;
    }
    //
    $("#GetZIP").click(function ()
    {
        try {
            //
            _ShowProgressBar();
            //
            var p_url = "SetZipAsync";
            //
            $.ajax(
                {
                    url   : p_url,
                    async : true,
                    global: true
                })
                .done(function (msg)
                {
                    //
                    _HideProgressBar();
                    //
                    var filePath = DebugHostingContent(msg);
                    //
                    console.log("SET_ZIP_ASYNC. ZIP PATH : " + filePath);
                    //
                    $("#DownloadFile").attr("href", "javascript:void window.open('" + filePath + "');");
                    //
                    alert('SE GENERÓ CORRECTAMENTE EL ARCHIVO');
                    //
                }
           );
        }
        catch (error)
        {
            //
            alert("ERROR EN ARCHIVO ZIP");
            //
            console.error(error);
        }
        //
    });
</script>