Application/SampleWebApplication/Controllers/Exam70483_4_DataAccessController.cs
using System;
using System.Web.Mvc;
using static _4_DataAccess.Skill_4_2_Consume_Data;

namespace Exam70483Web.Controllers
{
    #region "Classes"
    public class Exam70483_4_DataAccessController : Controller
    {
        #region "Principales"
        //
        public ActionResult Skill_4_2_Consume_Data()
        {
            //
            try
            {
                // EL METODO ABAJO EXPUESTO TRABAJABA CON EL MODELO DE DATOS ANTERIOR
                // NO SE EXPONE A ESTA VISTA
                // 4_DATA_ACCESS.Skill_4_2(new string[0]);

                //
                // [Listing 4 - 25] - [Consume JSON Data] 
                //
                ImageOfDay imageOfDay = _4_DataAccess.Skill_4_2_Consume_Data.JsonTest();
                //
                ViewBag.Url     = imageOfDay.url;
                ViewBag.Message = @"[Listing 4-25] - [Consume JSON Data]";
                //
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
            }
            //
            return View();
        }
        //
        public ActionResult Skill_4_3_Linq()
        {
            try
            {
                //string constring = System.Configuration.ConfigurationManager.ConnectionStrings["defaultConnection"].ConnectionString;
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
            }
            //
            return View();
        }
        #endregion
    }
    #endregion
}

Application/SampleWebApplication/Controllers/MCSDController.cs
using System;
using System.Web.Mvc;

namespace Exam70483Web.Controllers
{
    public class MCSDController : Controller
    {
        //
        public ActionResult _MCSD()
        {
            try
            {
                //string constring = System.Configuration.ConfigurationManager.ConnectionStrings["defaultConnection"].ConnectionString;
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
            }

            return View();
        }
        //
        public ActionResult _Exam70483()
        {
            try
            {
                // SKILL 4.3 LINQ
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
            }
            //
            return View();
        }
    }
}

Application/SampleWebApplication/Views/MCSD/_Exam70483.cshtml
@{
    ViewBag.Title   = @"[MCSD] - [Exam Ref - 70-483]";
    ViewBag.Message = @"[Programming in C# - Second Edition]- [Rob Miles]";
}@Page

<div class="main-container">
    <div class="content">
        <div class="content-body">
            <p>@ViewBag.Title</p>
            <p>@ViewBag.Message</p>
        </div>
    </div>
    <div>
        <ul>
            <li>[Chapter 1 - Manage Program Flow]   </li>
            <li>[Chapter 2 - Create and Use Types]  </li>
            <li>[Chapter 3 - Debug and Security]    </li>
            <li>[Chapter 4 - Implement Data Access] </li>
                <ul>
                    <li>@Html.ActionLink("[SKILL 4.1 - I/O OPERATIONS] ", "_MCSD"                   , "MCSD")</li>
                    <li>@Html.ActionLink("[SKILL 4.2 - CONSUME DATA]   ", "Skill_4_2_Consume_Data"  , "Exam70483_4_DataAccess")</li>
                    <li>@Html.ActionLink("[SKILL 4.3 - LINQ]           ", "Skill_4_3_Linq"          , "Exam70483_4_DataAccess")</li>
                    <li>@Html.ActionLink("[SKILL 4.4 - SERIALIZATION]  ", "_MCSD"                   , "MCSD")</li>
                    <li>@Html.ActionLink("[SKILL 4.5 - COLLECTIONS]    ", "_MCSD"                   , "MCSD")</li>
                </ul>
            </li>
        </ul>
    </div>
</div>

Application/SampleWebApplication/Views/MCSD/_MCSD.cshtml
@{
    ViewBag.Title   = @"[MCSD] - [Microsoft Certified Solution Developer]";
    ViewBag.Message = @"[Certification Path]";
}@Page

<div class="main-container">
    <div class="content">
        <div class="content-body">
            <p>@ViewBag.Title</p>
            <p>@ViewBag.Message</p>
        </div>
    </div>
    <div>
        <p><a href="https://docs.microsoft.com/es-es/learn/certifications/mcsa-web-applications-certification">[MCSA - WEB APPLICATIONS]</a></p>
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("[Exam 70-483] - [Programming in C#]"  , "_Exam70483" , "MCSD")</li><br />
            <li>@Html.ActionLink("[Exam 70-486] - [ASP.NET MVC]"        , "_MCSD"      , "MCSD")</li><br />
            <li>@Html.ActionLink("[Exam 70-480] - [HTML/CSS/JSCRIPT]"   , "_MCSD"      , "MCSD")</li><br />
        </ul>
    </div>
</div>